name: Generate Pac-Man Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gerar gráfico Pac-Man
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: AmandaSserena   # <<< NOME DELA AQUI
          gameTheme: github-dark            # pode trocar por github, github-light
          outputFormat: svg
          speed: 2                          # 1 = lento, 2 = normal, 3 = rápido

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
