name: Generate Pac-Man

on:
  schedule:
    - cron: "0 0 * * *"   # Atualiza todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar Pac-Man
        uses: Platane/snk@v3
        with:
          github_user_name: AmandaSserena   # Trocar pelo user dela
          outputs: dist/pacman-dark.svg?palette=github-dark
          mode: eating
          color_snake: yellow   # cor do Pac-Man
          color_pellet: white   # cor dos pontos

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
