name: Generate Snake Game

on:
  workflow_dispatch:
  schedule:
    
    - cron: "0 22 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha
        uses: Platane/snk@v2
        with:
          github_user_name: amandasserena
          outputs: dist/snake.svg

      - name: Adicionar saída ao README
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist

